### ISSUE TITLE
It doesn't work..

### ISSUE THREAD

**Issue by W4J1e** [hexojs/hexo-deployer-rsync#85]
I have installed cwRsync on my windows server, and telnet ip+port showed everything goes well.
But I still cannot deploy my hexo to my server with hexo-deployer-rsync.
```
deploy:
  type: rsync
  host: 42.193.x.x
  user: rsync
  root: /cygdrive/c/test #this root I also tried "/"
  port: 41026 #I have changed the port
  delete: true
  verbose: true
  ignore_errors: false
```
But when I made hexo deploy, it showed that:

![1](https://user-images.githubusercontent.com/74824162/141666070-2edbeada-c8f9-4fec-a280-1c0fcd684f58.jpg)
